### ISSUE TITLE
BiConsumer access to clij2?

### ISSUE THREAD

**Issue by haesleinhuepf** [saalfeldlab/i2k2020-imglib2-advanced#1]
Hey @axtimwalde ,

thanks for adding this cool clij2 example here! I'm just wondering, how the BiConsumer can have access to the clij2 gateway, where the images are from?
https://github.com/saalfeldlab/i2k2020-imglib2-advanced/blob/62a51497fae4553017391d1ecd8a7faf211485b8/src/main/java/org/janelia/saalfeldlab/i2k2020/ops/CLIJ2FilterOp.java#L33

Background: All clij2 operations are technically static functions like this one:
https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/plugins/Absolute.java#L46

Would it be possible to make a TriConsumer, that also takes the clij2 gateway?

Thanks!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
To make myself clear: I'm looking for a way to pack a clij2-based workflow into an imglib2-based BiConsumer because only GPU-acceleration of long workflows pays off 😉

**Comment by axtimwalde** [comment]
I agree, the staticness of the clij2 API is not too helpful.  Somebody needs to know the clij2 gateway.  However, if you make a TriConsumer, then you win nothing because you have to create the Gateway yourself and outside of the TroConsumer which makes everything look like the example scripts.  So the only reasonable way that I could come up with is how I implemented this Op.  The op creates clij2 and calls the BiConsumer as needed.  The BiConsumer knows the Op and can ask it for the Gateway as needed.  This pattern requires that you first create the Op and then assign the BiConsumer with a reference to the op (or as a lambda that knows the Op from context as in the example).  The workflow in the BiConsumer can be as long as you please.  I had no good example, do you have one?

**Comment by axtimwalde** [comment]
You have to look into the example.  This code:
```java
clij2Filter.setFilter(
    (a, b) -> clij2Filter.getClij2().differenceOfGaussian(a, b, 4, 4, 4, 3, 3, 3));
```
can easily be
```java
clij2Filter.setFilter(
    (a, b) -> {
        final CLIJ2 clij2 = clij2Filter.getClij2();
        clij2.differenceOfGaussian(a, b, 4, 4, 4, 3, 3, 3));
        clij2.pokeMyEye(b, a, "thumb"));
        CLBuffer c = clij2.create(a);
        clij2.triCompose(a, b, c, 2, 3));
        ...
    });
```

**Comment by axtimwalde** [comment]
Or in other words: your search ends here because this is the solution ;).

**Comment by haesleinhuepf** [comment]
Beautiful! I wasn't aware that you can use it like this. I was afraid you're suggesting to click "Yes" here:

![PSX_20201205_092544](https://user-images.githubusercontent.com/12660498/101237802-e5701e00-36db-11eb-9351-99674bdb19a2.jpg)

I'll play a bit with it and will put and example with a longer workflow in the clij2-docs.

Thanks Stephan, that's a very useful example 🤩
